"""
Name: $PERSES/perses/models/BaseSignalModel.py
Author: Keith Tauscher
Date: 25 February 2017

Description: File containing a base class for all signal models. It implements
             a property blank_blob which allows for something to be returned if
             no blobs are generated by a given signal model.
"""
from .BaseModel import BaseModel

class BaseSignalModel(BaseModel):
    @property
    def blank_blob(self):
        if not hasattr(self, '_blank_blob'):
            raise NotImplementedError("The signal model cannot operate " +\
                                      "without being given a blank blob " +\
                                      "to return in the event of no blobs " +\
                                      "being generated.")
        return self._blank_blob
    
    @blank_blob.setter
    def blank_blob(self, value):
        self._blank_blob = value

